'use client'

// import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './provider'
import { useEffect, useState } from 'react'
import Loader from './loader'

const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const [showLoader, setShowLoader] = useState(true)

  useEffect(() => {
    if (document.readyState === 'complete') return setShowLoader(true)
    window.addEventListener('load', () => {
      setTimeout(() => {
        setShowLoader(true)
      }, 3000)
    })
  }, [])

  return (
    <html lang="en">
      <body className={inter.className}>
        {showLoader ? (
          <div
          //   style={{
          //     display: 'flex',
          //     justifyContent: 'center',
          //     alignItems: 'center',
          //     width: '100vw',
          //     height: '100vh',
          //     background: 'white',
          //     zIndex: '1000',
          //   }}
          // >
          //   <p
          //     style={{
          //       fontSize: '1.5rem',
          //       lineHeight: '1.5rem',
          //       fontWeight: 500,
          //       color: 'black'
          //     }}
          >
            <Loader />
            {/* </p> */}
          </div>
        ) : (
          <>{children}</>
        )}
      </body>
    </html>
  )
}
